name: gym_management_system
description: Gym management mobile app for trainer use.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Fonts and Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  iconsax_flutter: ^1.0.1

  # Dependency Injection
  get_it: ^9.2.0
  equatable: ^2.0.7

  # Fire Base
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # Network manager(Internet connection)
  connectivity_plus: ^7.0.0
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_logo/app_logo.png
